### ISSUE TITLE
Release for 2.x?

### ISSUE THREAD

**Issue by valVk** [phalcon/incubator#293]
Hi,

I have a problem during ./composer.phar install

```
./composer.phar install                                                                       [17:43:12]
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phalcon/incubator dev-master -> satisfiable by phalcon/incubator[dev-master].
    - phalcon/incubator dev-master requires ext-phalcon >=1.2.4 -> the requested PHP extension phalcon has the wrong version (2.0.0r) installed.
```

**Comment by sergeyklay** [comment]
Fixed

**Comment by chrisgo** [comment]
I'm still getting the same error 

`composer require phalcon/incubator:dev-master`

**Comment by sergeyklay** [comment]
```sh
$ php -v
PHP 5.5.9-1ubuntu4.7 (cli) (built: Mar 16 2015 20:47:39) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

$ phalcon

Phalcon DevTools (2.0.0 RC 1)

Available commands:
  commands (alias of: list, enumerate)
  controller (alias of: create-controller)
  model (alias of: create-model)
  all-models (alias of: create-all-models)
  project (alias of: create-project)
  scaffold
  migration
  webtools

$ composer require phalcon/incubator

Using version ~1.3 for phalcon/incubator
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing swiftmailer/swiftmailer (v5.4.0)
    Loading from cache

  - Installing phalcon/incubator (v1.3.4)
    Downloading: 100%         

Writing lock file
Generating autoload files

```

**Comment by hthtung90** [comment]
>composer require phalcon/incubator:dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phalcon/incubator dev-master -> satisfiable by phalcon/incubator[dev-
master].
    - phalcon/incubator dev-master requires swiftmailer/swiftmailer ~5.2 -> no matching package foun
d.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setti
ng
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
